### ISSUE TITLE
태블릿 페이지 컨텐츠 균일 배치

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#10]
고생 많으십니다.

정기간행물, 기부소식 등 태블릿 페이지에서 컨텐츠가 없지 않는 한 기본 4개가 표시되게 구현 부탁드리겠습니다.

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
고생하셨습니다. 

모바일에서 썸네일 334px부터 커지는 방향으로 비율이 깨지는데
썸네일 올리는 비율을 지정하고 출력이미지 사이즈 고정하는 등 방법 검토 부탁드립니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

고생하셨습니다. 

소식지 부분은 모바일에서 썸네일 334px부터 커지는 방향으로 비율이 깨지는데
썸네일 올리는 비율을 지정하고 출력이미지 사이즈 고정하는 등 방법 검토 부탁드립니다.
아래쪽에 비율 관련 이슈에서 한번에 처리하게 된다면 이 이슈는 클로즈 하겠습니다.
