### ISSUE TITLE
기부하기 카드패널, 기부하기 버튼 관련

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#11]
고생많으십니다.

기부하기 카드패널
1. 메인에서 반전시 흰색, 기부프로그램에서 반전시 시안과 같은 회색으로 표현할 수 있는지 검토 부탁드립니다.
2. 반전된 패널에서 기부하기 눌렀을때 버튼이 테두리만 색칠되어있는데 버튼내부를 색칠 할 수 있는지 검토 부탁드립니다.
3. 기부유형의 기부하기 버튼은 폰트가 미적용 되었습니다.
4. 밑에서 올라오는 모션이 적용 가능한지 검토 부탁드립니다.

전체적 규칙은 아래 링크를 참고해 주시기 바랍니다.
  - [버튼/박스/기타요소 바로가기](https://xd.adobe.com/view/26be83b6-2348-4c67-ab75-79010b78b03e-73ed/screen/16e5984f-0afa-47fe-9ab2-ca01317e9622/specs/)
  - [어플리케이션 바로가기](https://xd.adobe.com/view/26be83b6-2348-4c67-ab75-79010b78b03e-73ed/screen/0ec414bc-3a19-4355-8291-993fc2928279/specs/)

감사합니다.

**Comment by SweepHee** [comment]
4번 모션은 카드반전 시 올라오는 모션으로 생각됩니다. 
작업 가능하나 우선순위는 나중으로 미루겠습니다...!

**Comment by SweepHee** [comment]
4번 제외 완료했습니다.

**Comment by fund-donga** [comment]
> 4번 제외 완료했습니다.

고생하셨습니다. 4번은 바쁜거 종료이후에 이슈 재오픈 하겠습니다.
