### ISSUE TITLE
디테일이슈 - 아이콘 텍스트 조합의 간격

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#12]
동아대 김대현입니다.

아이콘 텍스트 조합의 경우 간격을 최소 8px가 나오게 적절히 조절해 주시기 바랍니다.

ex) http://168.115.33.95/fund/type 전화아이콘과 전화번호 사이 간격

상세한 간격은 각 시안을 참고 바랍니다.

디테일 이슈로 우선순위는 아닙니다.

감사합니다.

**Comment by SweepHee** [comment]
기부유형 페이지에서 아이콘과 글자 간격 수정했습니다.
다른 페이지에서도 보이는 데로 수정하겠습니다.

**Comment by fund-donga** [comment]
> 기부유형 페이지에서 아이콘과 글자 간격 수정했습니다.
> 다른 페이지에서도 보이는 데로 수정하겠습니다.

감사합니다.
