### ISSUE TITLE
약정서 페이지 이슈  (작업 완료후 작성 예정)

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#13]
약정서 페이지는 작업이 완료되면 댓글 부탁드립니다.

이후에 수정사항 업데이트 하겠습니다.

감사합니다.

**Comment by SweepHee** [comment]
마크업까지 완료했고 클릭효과, 값 검증 효과 등은 기능 구현 시 작업 예정입니다.

**Comment by fund-donga** [comment]
예 잘 알겠습니다.

1. 현재까지 중에서 이슈는 파란 BG영역 최 우측상단에 체크 아이콘 확인 부탁드립니다.
2 .각 폼들의 간격은 기능 구현시 조정 부탁드립니다.
3. 복잡해서 어려움을 겪고 계신가요 텍스트는 기능 구현시 수정 텍스트 송부드리겠습니다.

현재까지는 주요 이슈가 없고 잘 만들어졌습니다. 감사합니다.
클로즈하고 기능 구현시 다시 리오픈 하겠습니다.
