### ISSUE TITLE
기부유형 파트 메뉴 수정

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#14]
고생 많으십니다.

현재 컨텐츠구성과  메뉴구성 (ex 전화/팩스/이메일)가 맞아 떨어지지 않아 기부유형 파트를 메뉴 수정을 검토중입니다.

링크 클릭할 경우 컨텐츠 위치로 스크롤 이동으로 구현 부탁드립니다.

확정되면 이 이슈는 클로즈 하고 새롭게 올리겠습니다.

**Comment by SweepHee** [comment]
링크 클릭 시 스크롤 이동 완료했습니다.

**Comment by fund-donga** [comment]
> 링크 클릭 시 스크롤 이동 완료했습니다.

고생하셨습니다.
