### ISSUE TITLE
기부유형 페이지 서면 파트 폰트크기, 아이콘 이슈

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#16]
기부유형 파트 서면파트의

dongafund 등의 폰트크기 확인 부탁드립니다.

카카오톡 아이콘은 아래의 링크의 이미지로 부탁드립니다.

[바로가기 publishing_img.md](publishing/img/publishing_img.md)

감사합니다.

**Comment by SweepHee** [comment]
안녕하세요,

서면 파트가 어떤 부분인가요?

**Comment by SweepHee** [comment]
기부 유형 파트 수정 완료했습니다.

**Comment by fund-donga** [comment]
> 기부 유형 파트 수정 완료했습니다.
![image](https://user-images.githubusercontent.com/84650160/120435001-2362ac00-c3b8-11eb-9a57-900bd05a55ef.png)

고생하셨습니다.
서면 파트의 경우
PC버전에서 다른쪽 안내 텍스트와 폰트사이즈가 다른데 한번 체크 부탁드립니다.

**Comment by SweepHee** [comment]
완료했습니다
