### ISSUE TITLE
PC 메뉴의 세제혜택 부분 미적용

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#17]
PC버전 메뉴바의

회색영역 세제혜택 부분이 미적용 되었습니다. 검토 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
https://xd.adobe.com/view/26be83b6-2348-4c67-ab75-79010b78b03e-73ed/screen/421114a5-4633-4744-baf6-0b89a727e4b4

![image](https://user-images.githubusercontent.com/84650160/120435428-aa178900-c3b8-11eb-9a93-25facda129d2.png)

위 영역입니다. 한번 검토해 주셔요

**Comment by SweepHee** [comment]
완료했습니다
