### ISSUE TITLE
전체 검정 #555폰트의 가독성 검토

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#18]
동아대 김대현입니다.

메인 텍스트 컬러로 쓰이는 #555폰트의 너무 연한지 팀장님 검토 한번 부탁드립니다.

감사합니다.

**Comment by puj090** [comment]
모니터에 따라 선명도가 달라서 원하시는 컬러 있으시면 전달주시면 재설정 하면 될 것 같습니다.

**Comment by fund-donga** [comment]
넵 일단 이슈 클로즈하고 추후에 이야기 나오면 다시 재오픈 하겠습니다. 감사합니다.
