### ISSUE TITLE
프로그램별 홍보, SMS 발송이 용이한 기부프로그램 URL

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#19]
기부프로그램을 추후 생성시 URL이
fund.donga.ac.kr/donga100
혹은
fund.donga.ac.kr/c/donga100

과 같이 짧은 주소로 해당프로그램의 약정페이지로 접근할 수 있게 작업 부탁드립니다.

사유는 해당 url이 80byte sms내에 메세지와 함께 들어가야 합니다.

donga100과 같은 키워드는 관리자페이지에서 입력 예정입니다.
텍스트가 너무 길어질 우려가 있으면 숫자로도 세팅 가능 할 것 같습니다.

검토 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
안녕하세요.

사이트에서 노출되는 기본 주소가 있고 

글 작성할 때 입력한 짧은 url로 해당 경로에 접속할 수 있게 작업 가능합니다.

예를들어 사이트에서 노출되는 주소는

fund.donga.ac.kr/support/campaign/1 이지만

글 작성할 때 짧은 url로 1을 입력했다면

fund.donga.ac.kr?a=1 
혹은 
fund.donga.ac.kr/a/1   의 형태로 접근 가능하게 작업할 수 있습니다.

형태는 말씀주시면 거기에 맞추도록 하겠습니다

**Comment by fund-donga** [comment]
> 안녕하세요.
> 
> 사이트에서 노출되는 기본 주소가 있고
> 
> 글 작성할 때 입력한 짧은 url로 해당 경로에 접속할 수 있게 작업 가능합니다.
> 
> 예를들어 사이트에서 노출되는 주소는
> 
> fund.donga.ac.kr/support/campaign/1 이지만
> 
> 글 작성할 때 짧은 url로 1을 입력했다면
> 
> fund.donga.ac.kr?a=1
> 혹은
> fund.donga.ac.kr/a/1 의 형태로 접근 가능하게 작업할 수 있습니다.
> 
> 형태는 말씀주시면 거기에 맞추도록 하겠습니다

답변주신대로 진행하고 추후에 확정하면 새로운 이슈로 말씀드리겠습니다. 감사합니다.

**Comment by fund-donga** [comment]
fund.donga.ac.kr/give0000/
을 기본 형태로 두고

fund.donga.ac.kr/give0000/136620
과 같이 직번을 넣어 접근 할 경우 추천인을 인식되도록 부탁드립니다.
