### ISSUE TITLE
결제대행사 관련 이슈

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#20]
아임포트, 부트페이 이용시

키오스크쪽이 JS 호출하여 화면 구현할 때 제약사항이 많아 REST API 방식으로만 구현할 수 있는 방안 모색중입니다.

내일 키오스크 업체와 미팅, 나이스페이와 직접 계약 관련 검토 예정입니다.

관련 미팅과 나이스페이 측 API문서 수령하여 검토/확정된 후 말씀드리겠습니다.

네이버페이는 이번 과업에서는 개발 안하기로 교내 컨펌 받았습니다.

현재까지 대안
1. 나이스페이 가입 (신용카드, 카카오페이 서비스)
2. 나이스페이, 카카오페이 각각 가입
3. 부트페이 이용
4. 이도저도 안되면 기존 효성FMS 카드만 구현

감사합니다.

**Comment by SweepHee** [comment]
넵 확인했습니다.
