### ISSUE TITLE
기부하기 패널의 기부하기 버튼 위치

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#21]
기부하기패널의

기부하기 버튼이 바깥쪽 border 라인 상하좌측 패딩이 동일하게 움직일 수 있도록 부탁드립니다.

PC/모바일 버전에서 심볼로고의 세로 위치를 1~2px 올려 주시면 감사하겠습니다.
![image](https://user-images.githubusercontent.com/84650160/120435818-25793a80-c3b9-11eb-977f-36dba3a36f38.png)

**Comment by SweepHee** [comment]
완료했습니다
