### ISSUE TITLE
결제대행사 사전 심사를 위한 기부하기 페이지 우선작업

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#22]
결제대행사 심사를 위해 기부하기 페이지를 우선적으로 작업 부탁드립니다.

기부를 직접 일으키거나 모듈을 연결시키는 단계까지는 아니더라도 진행되는 모습을 볼 수 있도록 조치 부탁드립니다.

네이버페이 주석처리 부탁드립니다.

분할 납부도 일단 시안대로 구현은 부탁드립니다.

접근 시 카카오페이 인증이 들어가야할
기부금 영수증/기부내역조회 등의 페이지도 작업 부탁드립니다. (다음 누르면 들어갈 수 있도록)

**Comment by puj090** [comment]
결제대행사 사전 심자를 위한 작업 범위

기부프로그램PC(39페이지) 특정 썸네일 클릭시 -> 약정서PC(27페이지) 버튼 클릭시 그에 맞는 항목들 노출 -> 전자서명PC(30페이지) 값을 넣을 순 있지만 클릭시 준비중이라는 알람창 노출

완료 예정일 : 6월 10일

**Comment by SweepHee** [comment]
완료했습니다
