### ISSUE TITLE
4k 해상도에서의 메인 비쥬얼 화면 깨짐

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#24]
빠듯한 일정에 고생 많으십니다.

4k해상도에서 메인비쥬얼이 깨지는 현상 한번 체크 부탁드리겠습니다.

감사합니다.

![제목 없음-1](https://user-images.githubusercontent.com/84650160/120468047-c5e05680-c3db-11eb-9919-b9660cecf7a7.png)

**Comment by SweepHee** [comment]
수정했습니다.

**Comment by fund-donga** [comment]
> 수정했습니다.

고생많으셨습니다. 메인을 1920기준 하단부 뉴스가 조금 보이게 하려는 의도로 세로 800픽셀로 시안을 잡았었는데
그렇게 맞출수 있을지 한번 검토 부탁드립니다.

픽셀이 딱딱 맞지 않아도 혹시 아래쪽 컨텐츠를 조금이나마 사용자가 확인할 수 있으면 좋겠습니다.
