### ISSUE TITLE
네이버페이 버튼 활성화

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#29]
고생 많으십니다.

각 PG사 입점 시 계속해서 학교법인의 승인을 받아야 해서 한번에 처리하고자 합니다.

네이버페이 입점심사를 위해 약정서 페이지 네이버페이 버튼을 활성화 부탁드리겠습니다.

감사합니다.

**Comment by puj090** [comment]
노출된 상태입니다.

**Comment by fund-donga** [comment]
> 노출된 상태입니다.
고생 많으셨습니다.
