### ISSUE TITLE
이미지 늘어나고 줄어들 때 비율고정 검토

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#3]
고생 많으십니다.

반응형 이미지 비율 유지 고정시키면서 확대 축소가 가능한지 검토 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
부분적으로 가능할 것 같습니다.
모든 업로드 되는 이미지의 가로 세로 비율이 같다면 적용이 가능할 것으로 보이나
기부소식페이지의 썸네일처럼 이미지의 비율이 다를 수 있다면 세로크기는 고정해야할 것으로 보입니다

**Comment by fund-donga** [comment]
고생많으십니다.
기부소식은 업로드 시 4:3으로 고정 비율로 올리겠습니다.
기부프로그램 쪽은 썸네일은 1:1로 맞추어 올리고 전체 큰이미지는 어떻게할지 고민 해 보고 말씀드리겠습니다.

**Comment by SweepHee** [comment]
이미지 크기 말씀해주시면 그 크기에 맞게 나오게 하겠습니다

**Comment by fund-donga** [comment]
> 이미지 크기 말씀해주시면 그 크기에 맞게 나오게 하겠습니다

메인은 PC 1920*800 px, 태블릿 가로값*800px, 모바일 가로값 * 600px 입니다.
전화로 세부내용 말씀드리고 가능여부 여쭈어보겠습니다.
