### ISSUE TITLE
서브메뉴 하위 카테고리 가로스크롤 적용 부탁드립니다.

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#4]
고생 많으십니다.

서브메뉴 하위 카테고리쪽에도 가로스크롤 적용 부탁드립니다.

http://168.115.33.95/news
http://168.115.33.95/support

감사합니다.

**Comment by SweepHee** [comment]
![dongfund1](https://user-images.githubusercontent.com/44694633/120254608-2af55880-c2c5-11eb-8f7c-39ea238e80d0.gif)

이 부분 말씀하시는 거 맞으실까요?

**Comment by fund-donga** [comment]
안녕하십니까, 전체보기 기부소식 쪽 모바일로 갔을때의 가로스크롤 입니다.

네이버 스마트어라운드의 구동화면 참고 부탁드리겠습니다.
https://s.search.naver.com/p/around/search.naver?tab=cafe

감사합니다.

**Comment by SweepHee** [comment]
![3](https://user-images.githubusercontent.com/44694633/120260303-97298980-c2d0-11eb-93bc-7f0764ba76b3.gif)

현재는 이런 형태로 되고 있는데 다른 효과가 필요하실까요?

**Comment by fund-donga** [comment]
아 제가 PC에서 줄이고 늘리고 하다보니 잘못 본 것 같습니다.
잘못 알았습니다. 감사합니다.
![캡처](https://user-images.githubusercontent.com/84650160/120260554-14ed9500-c2d1-11eb-84d0-76f8f620cce8.JPG)

가로스크롤 2개 상하단 중 상단쪽만 가로스크롤이 생기는데 이것만 좀 살펴봐 주셔요.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

감사합니다.
