### ISSUE TITLE
admin 추가계정 생성 요청

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#49]
admin 계정 4개 추가 생성 요청드립니다.

임시로 사용하고 

fund.donga.ac.kr로 이관이후에는 직번 로그인으로 변경 예정입니다.

**Comment by ghost** [comment]
임시로
admin2 / 12345678
admin3 / 12345678
admin4 / 12345678
admin5 / 12345678
추가했습니다.
