### ISSUE TITLE
명예의 전당과 기부자 예우 페이지 서로 교체 후 명예의 전당 숨김

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#5]
고생 많으십니다.

명예의 전당과 기부자 예우 페이지가 서로 바뀌어야 합니다.

명예의 전당페이지는 현재 개인정보 문제로 검토중이니 숨김처리 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

고생하셨습니다.
