### ISSUE TITLE
푸터 수정사항 및 링크주소

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#6]
안녕하십니까, 동아대 김대현입니다.
고생 많으십니다.

푸터 수정사항입니다.

푸터 

시안에는 라인이 있는데 라인이 미적용 되었습니다.

간격 한번 봐주십시오.

사업자등록번호 수정 603-82-01274

링크
동아대학교 donga.ac.kr
동아대학교병원 damc.or.kr
동아대학교대신요양병원 www.daudh.or.kr
동아대학교총동문회 dongmun.donga.ac.kr
개인정보처리방침 https://donga.ac.kr/gzSub_014.aspx

푸터아이콘
참고 https://news.samsung.com/kr/
https://img.global.news.samsung.com/image/icon_svg/ico_googlenews_wh.svg

PC 버전 배경이미지 xd에서 다운로드 받으셔서 적용 부탁드립니다. (산 윗부분 음영 제거 된 버전입니다.)

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

고생하셨습니다.
카카오 SVG 적용하니 깨지는 것 같은데 비율을 맞출수 있는지 살펴봐 주시고 불가하면 PNG로 부탁드립니다.

**Comment by fund-donga** [comment]
> > 완료했습니다.
> 
> 고생하셨습니다.
> 카카오 SVG 적용하니 깨지는 것 같은데 비율을 맞출수 있는지 살펴봐 주시고 불가하면 PNG로 부탁드립니다.
기부유형 페이지도 카카오 SVG가 깨지는 것 같습니다.

**Comment by SweepHee** [comment]
저희 쪽에서는 깨지는게 확인이 안되는데 어떻게 깨지는지 볼 수 있을까요?

**Comment by fund-donga** [comment]
> 저희 쪽에서는 깨지는게 확인이 안되는데 어떻게 깨지는지 볼 수 있을까요?

정상작동합니다.

1. 웹사이트 링크는 새창으로 부탁드립니다.
2. 동아대학교 로고 SVG 적용 부탁드립니다.
https://github.com/fund-donga/web_renewal/blob/main/publishing/img/%EB%8F%99%EC%95%84%EB%8C%80%ED%95%99%EA%B5%90ui.svg
3. 모금아이디어 제안 제거 부탁드립니다.
4. 담당자 안내 주석처리 부탁드립니다.
5. 반응형 태블릿/모바일 접속시 적용시 좌우 마진값을 부탁드립니다. 픽셀기준 (24~5px)
6. "상호명 줄바꿈 동아대학교" 형태로 되어있는 부분들 시안과 같이 줄바꿈이 없도록 부탁드립니다.
7. 반응형 태블릿, 모바일 모드에서는 링크아이콘이 센터정렬로 작업 부탁드립니다.
8. 카카오톡 http://pf.kakao.com/_PNbKs 이메일 fund@donga.ac.kr 유튜브 https://www.youtube.com/channel/UCYXWpF0ptQvQYSZlo41CPmg 인스타 https://www.instagram.com/donga_univ/ 
9. font-weight: bold 설정 되있는부분 한번 확인 부탁 드립니다.

![image](https://user-images.githubusercontent.com/84650160/127479281-539d4e99-a8aa-4c32-8b43-d78260ee7748.png)

![image](https://user-images.githubusercontent.com/84650160/127611150-2eef418b-624d-4964-ba42-e6cf6687d409.png)
