### ISSUE TITLE
기부프로그램 > 단과대 학과 지원 셀렉트 버튼 부분

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#7]
안녕하십니까, 동아대 김대현입니다.

기부 프로그램 > 단과대 학과 지원 셀렉트 버튼 부분이 시안과 좀 다르게 구현 되었습니다.

한번 살펴봐 주시기 바랍니다.

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

고생하셨습니다.
