### ISSUE TITLE
기부하기 페이지 대학 발전 전반에 기부 폰트 미적용

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#8]
안녕하십니까, 동아대 김대현입니다.

기부하기 페이지 "대학 발전 전반에 기부" 텍스트에 폰트 미적용 되어있습니다.

검토 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
완료했습니다.

**Comment by fund-donga** [comment]
> 완료했습니다.

고생하셨습니다.
