### ISSUE TITLE
기부자 라운지 > 이달의 기부자 컨텐츠 스크롤 미적용, 성명 가운데 별표 처리 요청

### ISSUE THREAD

**Issue by fund-donga** [fund-donga/web_renewal#9]
안녕하십니까, 고생 많으십니다.

기부자 라운지 > 이달의 기부자 페이지에
컨텐츠 스크롤이 미적용 되었습니다.

법인/개인 중 개인의 성명 첫글자와 마지막 글자 사이를 별표처리 부탁드립니다.

감사합니다.

**Comment by SweepHee** [comment]
모금현황의 이달의 기부자 부분 수정했습니다.

**Comment by fund-donga** [comment]
> 모금현황의 이달의 기부자 부분 수정했습니다.

고생하셨습니다.
